apiVersion: v1
kind: Service
metadata:
  name: ai-client
  namespace: ai-gitops
spec:
  selector:
    app: ai-client
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

