apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-client
  namespace: ai-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-client
  template:
    metadata:
      labels:
        app: ai-client
    spec:
      containers:
        - name: ai-client
          image: supraa23/ai-client:1.0
          ports:
            - containerPort: 5000
